### ISSUE TITLE
Bug: Crash on startup

### ISSUE THREAD

**Issue by qin-nz** [hua1995116/linec#2]
Just run `linec` and then

```
C:\Users\qin-nz\AppData\Roaming\npm\node_modules\linec\lib\linec.js:196
    var colorMax = [maxLine[0].yellow, ('' + maxLine[1]).yellow, ('' + maxLine[2]).yellow, ('' + maxLine[3]).yellow];
                           ^

TypeError: Cannot read property '0' of undefined
    at hanldeTable (C:\Users\qin-nz\AppData\Roaming\npm\node_modules\linec\lib\linec.js:196:28)
    at linec (C:\Users\qin-nz\AppData\Roaming\npm\node_modules\linec\lib\linec.js:363:21)
    at Object.<anonymous> (C:\Users\qin-nz\AppData\Roaming\npm\node_modules\linec\lib\index.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Comment by qin-nz** [comment]
这个 bug 还是高优处理下吧，
这个会在一些文件夹里出现，但因为不懂 js，所以不太能帮助定位

**Comment by hua1995116** [comment]
OK，我处理一下

**Comment by hua1995116** [comment]
npm i -g linec@1.3.7 试试

**Comment by qin-nz** [comment]
1.3.7 不报错了，但是结果没东西

```
T=0.024 s (0.0 files/s 0.0 lines/s)
--------------------------------------------------
language            files     blank      code

SUM                     0         0         0
--------------------------------------------------
```

**Comment by qin-nz** [comment]
我的是 Windows 系统
在文件夹 `xxx` 这个路径下运行是无结果的，我尝试把当前文件夹的名称从 `xxx` 改成了 `xxx-1` 就能正常看到输出了。

**Comment by hua1995116** [comment]
你的文件名有什么特殊的吗

**Comment by qin-nz** [comment]
@hua1995116 没有，除了盘符 `C:`，只有英文字母和分隔符，Windows 上是 `\`

**Comment by hua1995116** [comment]
我用 windows 试试

**Comment by hua1995116** [comment]
@qin-nz 你方便加个联系方式么，需要你的帮助调试。因为我本地测试是ok的

**Comment by qin-nz** [comment]
我用`console.log`调试了你的代码，找到问题了，是 `.gitignore` 的问题。具体如下：

背景：Go 语言用 `go build` 生成的可执行文件默认是和当前文件夹同名的，为了避免二进制被提交，需要在 `.gitignore` 中排除这个文件。

我看你的代码尝试解析了 `.gitignore`，然后把和文件夹同名的那个文件名列入了忽略列表。
这就带来了潜在问题，如果你在 mac/linux 上在 .gitignore 中写个 home 或者 Windows 中 写个 Users，那么整个目录都会被忽略。

建议：把 cPath 改成基于当前目录（更准确些是 `--path` 指定路径）的相对路径格式（当然，因为改成了相对路径，不确定其他地方是否需要一同修改） ```ig.ignores(cPath);```

**Comment by hua1995116** [comment]
@qin-nz 我有点迷惑，在 .gitignore 写个 home ，那么当前的 home 被忽略应该是正常的吧? 等不能提供下你的代码目录树。。我看下到底是为啥

**Comment by qin-nz** [comment]
@qin-nz 

> 在 .gitignore 写个 home ，那么当前的 home 被忽略应该是正常的吧? 

是的，正常，但它实际上会把  `/home` 都忽略了，而不仅仅是当前目录下的 `home`

**Comment by qin-nz** [comment]
我的场景是在 
`C:\Users\qin-nz\xxx\.gitignore` 内容包含 `xxx`，希望忽略的是 `C:\Users\qin-nz\xxx\xxx`，但实际上 `C:\Users\qin-nz\xxx` 这整个目录（也就是我运行 `linec` 的目录）都被忽略了。

**Comment by hua1995116** [comment]
奥。这个意思，我测试一下， 也就是 .gitignore 作用范围被扩大了。

**Comment by qin-nz** [comment]
是的，至少在Windows上如此。

**Comment by hua1995116** [comment]
@qin-nz `npm i linec@latest -g` 升级到最新版，这个问题解决了，唔，抱歉，最近有点忙，这么久了才修复。

**Comment by hua1995116** [comment]
`npm i linec@latest -g` 升级到最新版，这个问题解决了，唔，抱歉，最近有点忙，这么久了才修复。

**Comment by qin-nz** [comment]
我感觉你改完之后，好像 `.gitignore` 完全失效了

**Comment by hua1995116** [comment]
是的，有个变量写错了，源码运行是正常的，打包完用了严格模式，导致出错了。 测试用例还是很重啊 - - ，后面得补一补，太折腾了。 升级了 1.3.11

**Comment by qin-nz** [comment]
@hua1995116 非常感谢，现在可用啦
